name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["*"]

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  AUTH_KEY: ${{ secrets.AUTH_KEY }}
  FROM_NUMBER: ${{ secrets.FROM_NUMBER }}


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # - name: Run integration tests
    #   uses: docker://python:3.8
    #   env:
    #     DISCORD_TOKEN: ${{ env.DISCORD_TOKEN }}
    #     API_KEY: ${{ env.API_KEY }}
    #     AUTH_KEY: ${{ env.AUTH_KEY }}
    #     FROM_NUMBER: ${{ env.FROM_NUMBER }}
    #   run: |
    #     python -m pytest tests/integration
        
    - name: Build Docker Image
      run: |
        docker build -t discord-sms-bot .
      env:
        DISCORD_TOKEN: ${{ env.DISCORD_TOKEN }}
        API_KEY: ${{ env.API_KEY }}
        AUTH_KEY: ${{ env.AUTH_KEY }}
        FROM_NUMBER: ${{ env.FROM_NUMBER }}

    - name: Run tests
      run: |
        docker run discord-sms-bot
