name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      API_KEY: ${{ secrets.API_KEY }}
      AUTH_KEY: ${{ secrets.AUTH_KEY }}
      FROM_NUMBER: ${{ secrets.FROM_NUMBER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
                
    - name: Build Docker Image
      uses: docker/build-action@v1
      with:
        context: .
        push: true
        tags: "discord-bot:${{ env.TAGS }}"
        build-args: |
          DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          API_KEY=${{ secrets.API_KEY }}
          AUTH_KEY=${{ secrets.AUTH_KEY }}
          FROM_NUMBER=${{ secrets.FROM_NUMBER }}